[GLOBAL]
pants_version = "2.11.0"

backend_packages = [
  "pants.backend.experimental.go",
  "pants.backend.docker",
]

[golang]
expected_version = 1.17

[docker.registries.ghcr]
address = ["ghcr.io"]
default = true

[docker]
build_args = ["GIT_BRANCH"]
